config/routes.rb
Rails.application.routes.draw do
  get 'plants/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :gardens do
    resources :plants, only: [:create]
  end

  resources :plants, only: :destroy do
    resources :completions, only: %i[new create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chore.rb
class Chore < ApplicationRecord
  has_many :completions, dependent: :destroy
end

app/models/completion.rb
class Completion < ApplicationRecord
  belongs_to :plant
  belongs_to :chore
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
  has_many :completions, dependent: :destroy

  validates :name, :image_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end



# As a user I can see one garden's plants -> Model Plant
# As a user I can add a plant in a garden -> Index garden, controller#create Plant
# As a user I can delete a plant -> #destroy Plant

app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
  def new
    @plant = Plant.find(params[:plant_id])
    @completion = Completion.new
  end

  def create
    @plant = Plant.find(params[:plant_id])
    chores = Chore.where(id: params[:completion][:chore_id])
    chores.each do |chore|
      @completion = Completion.new
      @completion.plant = @plant
      @completion.chore = chore
      @completion.save!
    end
    redirect_to garden_path(@plant.garden)
  end

  private

  def completion_params
    params.require(:completion).permit(:chore_id)
  end
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: %i[ show edit update destroy ]

  # GET /gardens or /gardens.json
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1 or /gardens/1.json
  def show
    @plant = Plant.new
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens or /gardens.json
  def create
    @garden = Garden.new(garden_params)

    respond_to do |format|
      if @garden.save
        format.html { redirect_to @garden, notice: "Garden was successfully created." }
        format.json { render :show, status: :created, location: @garden }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gardens/1 or /gardens/1.json
  def update
    respond_to do |format|
      if @garden.update(garden_params)
        format.html { redirect_to @garden, notice: "Garden was successfully updated." }
        format.json { render :show, status: :ok, location: @garden }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gardens/1 or /gardens/1.json
  def destroy
    @garden.destroy!

    respond_to do |format|
      format.html { redirect_to gardens_path, status: :see_other, notice: "Garden was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden
      @garden = Garden.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def garden_params
      params.require(:garden).permit(:name, :banner_url)
    end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_garden, only: [:create]
  def create
    @plant = Plant.new(plant_params)
    @plant.garden = @garden

    if @plant.save
      redirect_to garden_path(@garden)
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to garden_path(@plant.garden), status: :see_other
  end

  private

  def set_garden
    @garden = Garden.find(params[:garden_id])
  end

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/completions_helper.rb
module CompletionsHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/completions/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <h1>Complete a chore for <%= @plant.name %></h1>

      <%= simple_form_for [@plant, @completion] do |f| %>
        <%= f.association :chore, as: :check_boxes, label: "What did you do?" %>
        <%= f.submit "Complete", class: 'btn btn-primary' %>
      <% end %>

      <br>

      <% if @plant.completions.present? %>
        <h2><%= pluralize(@plant.completions.count, "chore") %> completed so far</h2>
        <ul>
          <% @plant.completions.order(created_at: :desc).each do |completion| %>
            <li>
              <em><%= completion.chore.name %></em>
              on <%= completion.created_at.strftime('%B %d, %Y %l:%M %p') %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/gardens/_form.html.erb
<%= form_with(model: garden) do |form| %>
  <% if garden.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(garden.errors.count, "error") %> prohibited this garden from being saved:</h2>

      <ul>
        <% garden.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :banner_url, style: "display: block" %>
    <%= form.text_field :banner_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/gardens/_garden.html.erb
<div id="<%= dom_id garden %>">
  <p>
    <strong>Name:</strong>
    <%= garden.name %>
  </p>

  <p>
    <strong>Banner url:</strong>
    <%= garden.banner_url %>
  </p>

</div>

app/views/gardens/edit.html.erb
<h1>Editing garden</h1>

<%= render "form", garden: @garden %>

<br>

<div>
  <%= link_to "Show this garden", @garden %> |
  <%= link_to "Back to gardens", gardens_path %>
</div>

app/views/gardens/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Gardens</h1>

<div id="gardens">
  <% @gardens.each do |garden| %>
    <%= render garden %>
    <p>
      <%= link_to "Show this garden", garden %>
    </p>
  <% end %>
</div>

<%= link_to "New garden", new_garden_path %>

app/views/gardens/new.html.erb
<h1>New garden</h1>

<%= render "form", garden: @garden %>

<br>

<div>
  <%= link_to "Back to gardens", gardens_path %>
</div>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @garden.banner_url %>');">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>


<div class="container">
  <div class="row">
    <% @garden.plants.each do |plant| %>
      <div class="col-4 mt-4">
        <div class="card-category d-flex justify-content-center align-items-center fw-bold" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url('<%= plant.image_url %>')">
          <%= plant.name %>
          <%= link_to "+", plant_path(plant), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'card-remove-link' %>

          <div class="chores">
            <% completion = plant.completions.last %>
            <% if completion.present? %>
              <span>
                Latest chore you've completed:
                <em><%= completion.chore.name %></em>
                on <%= completion.created_at.strftime('%B %d, %Y %l:%M %p') %>
            <% end %>
            <%= link_to new_plant_completion_path(plant) do %>
              <i class="fa-solid fa-check"></i>
            <% end %>
          </div>

        </div>
      </div>
    <% end %>
  </div>

  <div class="row justify-content-center my-5">
    <div class="col-4">
      <h4>Add a plant</h4>
      <%= simple_form_for [@garden, @plant] do |f| %>
        <%= f.input :name, placeholder: 'Palm tree' %>
        <%= f.input :image_url, placeholder: 'www.myfavoriteplant.com' %>
        <%= f.submit 'Add', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

<p style="color: green"><%= notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardensAndPlants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/create.html.erb
<h1>Plants#create</h1>
<p>Find me in app/views/plants/create.html.erb</p>